services:
  app_frontend:
    image: ${REGISTRY:-appfrontend}/appfrontend:${TAG:-latest}
    build:
      context: .
      dockerfile: Frontend/Frontend/Dockerfile
    ports:
      - '50000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - infrastructure_ultima-network
  
  
networks:
  infrastructure_ultima-network:
    external: true